"""add webhook delivery retry fields

Revision ID: 7690d7adce58
Revises: 19028279d660
Create Date: 2026-08-20 16:35:00.823661

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7690d7adce58'
down_revision: Union[str, None] = '19028279d660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_deliveries', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('webhook_deliveries', sa.Column('attempt_number', sa.Integer(), server_default='1', nullable=False))
    op.create_index(op.f('ix_webhook_deliveries_idempotency_key'), 'webhook_deliveries', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_deliveries_idempotency_key'), table_name='webhook_deliveries')
    op.drop_column('webhook_deliveries', 'attempt_number')
    op.drop_column('webhook_deliveries', 'idempotency_key')
    # ### end Alembic commands ###
